export const NOTION_TOKEN = process.env.NOTION_TOKEN;
export const NOTION_STOCK_DATABASE_ID = process.env.NOTION_STOCK_DATABASE_ID;
export const NOTION_ORDERS_DATABASE_ID = process.env.NOTION_ORDERS_DATABASE_ID;
